version: '3'

services:
  i-notes-frontend:
    command: ["npm", "run", "build"]
    networks:
      - reverse-proxy
    volumes:
      - public:/app/dist
networks:
  reverse-proxy:
    external: true
volumes:
  public:
    external: true