version: '3'

services:
  i-notes-frontend:
    command: ["npm", "run", "docker:prod"]
    newworks:
      - reverse-proxy
    volumes:
      /app/dist:/public/inotes
networks:
  reverse-proxy:
    external: true
volumes:
  public:
    external: true