version: '3'

services:
  i-notes-frontend:
    command: ["npm", "run", "build"]
    networks:
      - reverse-proxy
    volumes:
      - type: volume
        source: app/dist
        target: public
        volume:
          subpath: inotes

networks:
  reverse-proxy:
    external: true
volumes:
  public:
    external: true