version: '3'

services:
  i-notes-frontend:
    command: ["npm", "run", "build"]
    newworks:
      - reverse-proxy
    volumes:
      /app/dist:/usr/share/nginx/html/inotes
networks:
  reverse-proxy:
    external: true